management.endpoint.health.show-details: always

flyway:
  baseline-on-migrate: true
  baselineOnMigrate: true

spring:
  kafka:
    listener:
      missingTopicsFatal: false
    consumer:
      properties.spring.json.trusted.packages: com.example.demo.model
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: never

logging:
  level:
    org:
      springframework:
        boot:
          devtools:
            restart: DEBUG

management:
  info:
    env:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      discovery:
        enabled: true


testcontainers:
  postgresql:
    enabled: true
    image: postgres:14-alpine
  kafka:
    enabled: true
    image: confluentinc/cp-kafka:5.4.6
  redis:
    enabled: true
    image: redis:6-alpine
